---
# tasks file for ansible-role-memcached

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define memcached_user.
  set_fact:
    memcached_user: "{{ __memcached_user }}"
  when: memcached_user is not defined

- name: Define php_memcached_package.
  set_fact:
    php_memcached_package: "{{ __php_memcached_package }}"
  when: php_memcached_package is not defined

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Configure Memcached.
- name: Copy Memcached configuration.
  template:
    src: memcached-{{ ansible_os_family }}.conf.j2
    dest: "{{ memcached_config_file }}"
    owner: root
    group: root
    mode: 0644
  become: true
  tags: memcached
  notify: restart memcached


# - name: Memcached | PECL Library install
#   shell: printf "yes\n" | pecl install memcache creates=/usr/lib/php5/20100525/memcache.so
#   tags: memcached
#   become: true

# work in progress - manage the memcached.ini
# - name: Memcached | Config file for the PHP memcache extension
#   template:
#     src: php_apache2_memcached.ini.j2
#     dest: /etc/php5/apache2/conf.d/memcached.ini
#   tags: memcached
#   become: true


- name: Ensure Memcached is started and set to run on startup.
  service: name=memcached state=started enabled=yes