---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Install Memcached.
  apt:
    name: ['memcached', '{{ php_memcached_package }}']
    state: present
  become: true
  register: memcached_install
  notify: restart webserver
  tags: memcached
