---

- name: Install Memcached.
  yum:
    name: "{{ item }}"
    state: installed
    enablerepo: "{{ php_enablerepo }}"
  become: true
  with_items:
    - memcached
    - php-pecl-memcached
  notify: restart webserver
  tags: memcached

