---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Install Memcached.
  apt:
    name: {item}
    state: installed
  with_items:
    - memcached
    - php5-memcached
  sudo: true
