---

- name: Install Memcached.
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: "{{ php_enablerepo }}"
  become: true
  with_items:
    - memcached
    - "{{ php_memcached_package }}"
  notify: restart webserver
  tags: memcached

