---

- name: Install Memcached.
  yum:
    name: ['memcached', '{{ php_memcached_package }}']
    state: present
    enablerepo: "{{ php_enablerepo }}"
  become: true
  notify: restart webserver
  tags: memcached

