---
# handlers file for ansible-role-memcached

- name: restart memcached
  service: name=memcached state=restarted

- name: restart webserver
  action: service name={{ apache_daemon }} state=restarted
  tags: common
  sudo: true

